const crypto = require('crypto');
const { client } = require('./supabase');
const hash = (value) => { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(value, salt, 64).toString('hex')}`; };
const mapQuestion = (q) => ({ id: q.id, subject: q.subject, text: q.prompt, options: q.options, correct: q.correct_index });
async function attempts(db) { const { data, error } = await db.from('attempts').select('id,student_id,subject,score,total,correct,submitted_at').order('submitted_at', { ascending: false }).order('id', { ascending: false }); if (error) throw error; return new Map((data || []).filter((row, i, list) => list.findIndex((item) => item.student_id === row.student_id) === i).map((row) => [row.student_id, row])); }
async function state() { const db = client(); const [questions, students, latest] = await Promise.all([db.from('questions').select('id,subject,prompt,options,correct_index').order('id'), db.from('students').select('id,name,register_no,email').order('name'), attempts(db)]); if (questions.error) throw questions.error; if (students.error) throw students.error; return { questions: (questions.data || []).map(mapQuestion), students: (students.data || []).map((s) => { const a = latest.get(s.id); return { name: s.name, registerNo: s.register_no, email: s.email, status: a ? 'completed' : 'unattended', result: a ? { score: a.score, total: a.total, correct: a.correct, subject: a.subject, name: s.name, registerNo: s.register_no } : null }; }) }; }
async function student(input) { const db = client(); const row = { name: input.name.trim(), register_no: input.registerNo.trim(), email: input.email.trim().toLowerCase() }; if (input.password) row.password_hash = hash(input.password); const { error } = await db.from('students').upsert(row, { onConflict: 'register_no' }); if (error) throw error; return (await state()).students; }
async function teacher(input) { const db = client(); const { data, error } = await db.from('teachers').upsert({ name: input.name.trim(), email: input.email.trim().toLowerCase(), password_hash: hash(input.password) }, { onConflict: 'email' }).select('name,email').single(); if (error) throw error; return data; }
async function questions(input) { const list = Array.isArray(input.questions) ? input.questions : [input]; if (!list.length || !list.every((q) => q.subject && q.text && Array.isArray(q.options) && q.options.length === 4 && q.options.every(Boolean) && Number.isInteger(Number(q.correct)) && Number(q.correct) >= 0 && Number(q.correct) <= 3)) { const error = new Error('Each question needs a subject, prompt, four options, and valid correct answer.'); error.statusCode = 400; throw error; } const db = client(); const { error } = await db.from('questions').insert(list.map((q) => ({ subject: q.subject.trim(), prompt: q.text.trim(), options: q.options.map((option) => option.trim()), correct_index: Number(q.correct) }))); if (error) throw error; return (await state()).questions; }
async function attempt(input) { const db = client(); const lookup = await db.from('students').select('id,name,register_no,email').ilike('register_no', input.registerNo.trim()).single(); if (lookup.error || !lookup.data) { const error = new Error('Student is not registered.'); error.statusCode = 404; throw error; } const result = input.result; const inserted = await db.from('attempts').insert({ student_id: lookup.data.id, subject: result.subject, score: Number(result.score), total: Number(result.total), correct: Number(result.correct) || 0 }); if (inserted.error) throw inserted.error; return (await state()).students.find((s) => s.registerNo.toLowerCase() === lookup.data.register_no.toLowerCase()); }
module.exports = { state, student, teacher, questions, attempt };
